# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-docker-build-push
  description: Simple docker build action
  homepage: https://cloudposse.com/accelerate
  topics: ""

