name: 'Docker build and push'
description: 'Simple Docker build and push action'
author: hello@cloudposse.com
branding:
  icon: 'box'
  color: 'white'
inputs:
  workdir:
    description: 'Working directory'
    required: false
    default: './'
  file:
    description: 'Dockerfile name'
    required: false
    default: 'Dockerfile'
  organization:
    description: 'Organization'
    required: true
  repository:
    description: 'Repository'
    required: true
  registry:
    description: 'Docker registry'
    required: true
  login:
    description: 'Docker login'
    required: false
    default: ''
  password:
    description: 'Docker password'
    required: false
    default: ''
outputs:
  image:
    description: "Docker image name"
    value: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}
  tag:
    description: "Docker image tag"
    value: ${{ steps.context.outputs.tag }}
runs:
  using: "composite"
  steps:
    - id: context
      run: echo "::set-output name=tag::sha-${{ github.sha }}"
      shell: bash

    # docker context must be created prior to setting up Docker Buildx
    # https://github.com/actions-runner-controller/actions-runner-controller/issues/893
    - name: Set up Docker Context for Buildx
      shell: bash
      id: buildx-context
      run: |
        docker context create buildx-context || true 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        endpoint: buildx-context

    - name: Login
      uses: docker/login-action@v2
      if: ${{ contains(inputs.registry, '.amazonaws.com') || ( inputs.login != '' && inputs.password != '' ) }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.login }}
        password: ${{ inputs.password }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.workdir }}
        file: ${{ inputs.workdir }}/${{ inputs.file }}
        pull: true
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}:${{ steps.context.outputs.tag }}
        labels: org.opencontainers.image.source=https://github.com/${{ inputs.organization }}/${{ inputs.repository }}
